### ISSUE TITLE
Is windows supported?

### ISSUE THREAD

**Issue by precompiler** [JulzDiverse/aviator#24]
Hi,

I tried to build the project in Windows, but got following error. Does the project support windows?

github.com/JulzDiverse/aviator/vendor/code.cloudfoundry.org/commandrunner/linux_command_runner
..\github.com\JulzDiverse\aviator\vendor\code.cloudfoundry.org\commandrunner\linux_command_runner\linux_command_runner.go:27:11: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr
..\github.com\JulzDiverse\aviator\vendor\code.cloudfoundry.org\commandrunner\linux_command_runner\linux_command_runner.go:30:18: cmd.SysProcAttr.Setpgid undefined (type *syscall.SysProcAttr has no field or method Setpgid)
..\github.com\JulzDiverse\aviator\vendor\code.cloudfoundry.org\commandrunner\linux_command_runner\linux_command_runner.go:39:11: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr
..\github.com\JulzDiverse\aviator\vendor\code.cloudfoundry.org\commandrunner\linux_command_runner\linux_command_runner.go:42:18: cmd.SysProcAttr.Setpgid undefined (type *syscall.SysProcAttr has no field or method Setpgid)
..\github.com\JulzDiverse\aviator\vendor\code.cloudfoundry.org\commandrunner\linux_command_runner\linux_command_runner.go:51:11: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr
..\github.com\JulzDiverse\aviator\vendor\code.cloudfoundry.org\commandrunner\linux_command_runner\linux_command_runner.go:54:18: cmd.SysProcAttr.Setpgid undefined (type *syscall.SysProcAttr has no field or method Setpgid)

**Comment by JulzDiverse** [comment]
Hi @precompiler,

so unfortunately I never tested `aviator` on a windows machine before. I don't have a windows machine and also had no need for a windows version yet. 

I checked what the issue is and is coming from the `command_runner`. It is an explicit linux executor, and that is why you got those errors when trying to compile for windows. However, I replaced the code-line with a windows command runner to build the binary and uploaded it: [aviator-win](https://github.com/JulzDiverse/aviator/releases/download/v0.17.0/aviator-win) You could try this binary, but i cannot guarantee that it is working.

**Comment by precompiler** [comment]
Thanks very much for your help @JulzDiverse. I did some test, it works well so far.

**Comment by JulzDiverse** [comment]
@precompiler thx for opening this issue and giving me feedback. I'll will always add an windows binary of `aviator` in future.
